import type { BodyPart, ExerciseType } from "@/types/dailyforge";

export type CatalogCategory = "Push" | "Pull" | "Legs" | "Core" | "Cardio";

export interface CatalogExercise {
  name: string;
  category: CatalogCategory;
  bodyParts: BodyPart[];
  exerciseType: ExerciseType;
  sets: number;
  reps: number;
  perSetSeconds: number;
  sessionSeconds: number;
  notes: string;
}

export const CATALOG_CATEGORIES: CatalogCategory[] = [
  "Push",
  "Pull",
  "Legs",
  "Core",
  "Cardio",
];

export const CATALOG: CatalogExercise[] = [
  // ── PUSH ──────────────────────────────────────────────────
  {
    name: "Push-ups",
    category: "Push",
    bodyParts: ["Chest", "Arms"],
    exerciseType: "reps",
    sets: 3,
    reps: 12,
    perSetSeconds: 0,
    sessionSeconds: 60,
    notes: "Elbows tucked at 45°. Full range of motion — chest to floor.",
  },
  {
    name: "Knee Push-ups",
    category: "Push",
    bodyParts: ["Chest", "Arms"],
    exerciseType: "reps",
    sets: 3,
    reps: 12,
    perSetSeconds: 0,
    sessionSeconds: 60,
    notes:
      "Easier variation. Same form cues — straight line from head to knees.",
  },
  {
    name: "Diamond Push-ups",
    category: "Push",
    bodyParts: ["Chest", "Arms"],
    exerciseType: "reps",
    sets: 3,
    reps: 10,
    perSetSeconds: 0,
    sessionSeconds: 60,
    notes: "Hands together under chest. Triceps focus.",
  },
  {
    name: "Wall Push-ups",
    category: "Push",
    bodyParts: ["Chest", "Arms"],
    exerciseType: "reps",
    sets: 3,
    reps: 15,
    perSetSeconds: 0,
    sessionSeconds: 60,
    notes: "Beginner variation. Lean into the wall, push back.",
  },
  {
    name: "Tricep Dips",
    category: "Push",
    bodyParts: ["Arms"],
    exerciseType: "reps",
    sets: 3,
    reps: 12,
    perSetSeconds: 0,
    sessionSeconds: 60,
    notes: "Use a stable chair or bench. Elbows point straight back.",
  },
  {
    name: "Pike Push-ups",
    category: "Push",
    bodyParts: ["Shoulders", "Arms"],
    exerciseType: "reps",
    sets: 3,
    reps: 10,
    perSetSeconds: 0,
    sessionSeconds: 60,
    notes: "Hips high, head between hands. Shoulder press pattern.",
  },

  // ── PULL ──────────────────────────────────────────────────
  {
    name: "Superman",
    category: "Pull",
    bodyParts: ["Back", "Core"],
    exerciseType: "reps",
    sets: 3,
    reps: 12,
    perSetSeconds: 0,
    sessionSeconds: 60,
    notes: "Lift chest and legs off the floor. Squeeze glutes at the top.",
  },
  {
    name: "Reverse Snow Angels",
    category: "Pull",
    bodyParts: ["Back", "Shoulders"],
    exerciseType: "reps",
    sets: 3,
    reps: 12,
    perSetSeconds: 0,
    sessionSeconds: 60,
    notes: "Lie face down. Sweep arms from hips to overhead and back.",
  },
  {
    name: "Doorway Rows",
    category: "Pull",
    bodyParts: ["Back", "Arms"],
    exerciseType: "reps",
    sets: 3,
    reps: 12,
    perSetSeconds: 0,
    sessionSeconds: 60,
    notes: "Grip the doorframe. Lean back and pull chest to frame.",
  },

  // ── LEGS ──────────────────────────────────────────────────
  {
    name: "Squats",
    category: "Legs",
    bodyParts: ["Legs", "Glutes"],
    exerciseType: "reps",
    sets: 3,
    reps: 15,
    perSetSeconds: 0,
    sessionSeconds: 60,
    notes: "Knees track over toes. Chest up. Sit back and down.",
  },
  {
    name: "Lunges",
    category: "Legs",
    bodyParts: ["Legs", "Glutes"],
    exerciseType: "reps",
    sets: 3,
    reps: 12,
    perSetSeconds: 0,
    sessionSeconds: 60,
    notes: "Alternate legs. Back knee close to floor. Chest tall.",
  },
  {
    name: "Reverse Lunges",
    category: "Legs",
    bodyParts: ["Legs", "Glutes"],
    exerciseType: "reps",
    sets: 3,
    reps: 12,
    perSetSeconds: 0,
    sessionSeconds: 60,
    notes: "Step back instead of forward. Easier on the knees.",
  },
  {
    name: "Glute Bridges",
    category: "Legs",
    bodyParts: ["Glutes", "Legs"],
    exerciseType: "reps",
    sets: 3,
    reps: 15,
    perSetSeconds: 0,
    sessionSeconds: 60,
    notes: "Feet flat, hips drive up. Squeeze glutes hard at the top.",
  },
  {
    name: "Calf Raises",
    category: "Legs",
    bodyParts: ["Legs"],
    exerciseType: "reps",
    sets: 3,
    reps: 20,
    perSetSeconds: 0,
    sessionSeconds: 60,
    notes: "Full range. Pause at the top. Slow on the way down.",
  },
  {
    name: "Wall Sit",
    category: "Legs",
    bodyParts: ["Legs", "Glutes"],
    exerciseType: "timer",
    sets: 3,
    reps: 0,
    perSetSeconds: 45,
    sessionSeconds: 90,
    notes: "Thighs parallel to floor. Back flat against the wall.",
  },
  {
    name: "Jump Squats",
    category: "Legs",
    bodyParts: ["Legs", "Cardio"],
    exerciseType: "reps",
    sets: 3,
    reps: 12,
    perSetSeconds: 0,
    sessionSeconds: 90,
    notes: "Explode up. Land soft through the balls of your feet.",
  },

  // ── CORE ──────────────────────────────────────────────────
  {
    name: "Plank",
    category: "Core",
    bodyParts: ["Core"],
    exerciseType: "timer",
    sets: 3,
    reps: 0,
    perSetSeconds: 30,
    sessionSeconds: 90,
    notes: "Straight line from head to heels. Don't let hips sag.",
  },
  {
    name: "Side Plank",
    category: "Core",
    bodyParts: ["Core"],
    exerciseType: "timer",
    sets: 3,
    reps: 0,
    perSetSeconds: 30,
    sessionSeconds: 90,
    notes: "Stack hips. Lift bottom ribs. Switch sides between sets.",
  },
  {
    name: "Hollow Body Hold",
    category: "Core",
    bodyParts: ["Core"],
    exerciseType: "timer",
    sets: 3,
    reps: 0,
    perSetSeconds: 30,
    sessionSeconds: 90,
    notes: "Lower back pressed into floor. Arms and legs low.",
  },
  {
    name: "Crunches",
    category: "Core",
    bodyParts: ["Core"],
    exerciseType: "reps",
    sets: 3,
    reps: 15,
    perSetSeconds: 0,
    sessionSeconds: 60,
    notes: "Hands behind head — don't pull the neck. Curl the ribs.",
  },
  {
    name: "Sit-ups",
    category: "Core",
    bodyParts: ["Core"],
    exerciseType: "reps",
    sets: 3,
    reps: 15,
    perSetSeconds: 0,
    sessionSeconds: 60,
    notes: "Feet anchored. Full range — chest to knees.",
  },
  {
    name: "Bicycle Crunches",
    category: "Core",
    bodyParts: ["Core"],
    exerciseType: "reps",
    sets: 3,
    reps: 20,
    perSetSeconds: 0,
    sessionSeconds: 60,
    notes: "Slow and controlled. Elbow to opposite knee.",
  },
  {
    name: "Russian Twists",
    category: "Core",
    bodyParts: ["Core"],
    exerciseType: "reps",
    sets: 3,
    reps: 20,
    perSetSeconds: 0,
    sessionSeconds: 60,
    notes: "Rotate the torso, not just the arms. Chest up.",
  },
  {
    name: "Leg Raises",
    category: "Core",
    bodyParts: ["Core"],
    exerciseType: "reps",
    sets: 3,
    reps: 12,
    perSetSeconds: 0,
    sessionSeconds: 60,
    notes: "Keep lower back pressed down. Lower slowly.",
  },
  {
    name: "Dead Bug",
    category: "Core",
    bodyParts: ["Core"],
    exerciseType: "reps",
    sets: 3,
    reps: 10,
    perSetSeconds: 0,
    sessionSeconds: 60,
    notes: "Opposite arm and leg. Slow. Keep back flat.",
  },
  {
    name: "Bird Dog",
    category: "Core",
    bodyParts: ["Core", "Back"],
    exerciseType: "reps",
    sets: 3,
    reps: 10,
    perSetSeconds: 0,
    sessionSeconds: 60,
    notes: "Opposite arm and leg. Hold 2 seconds at full extension.",
  },
  {
    name: "Mountain Climbers",
    category: "Core",
    bodyParts: ["Core", "Cardio"],
    exerciseType: "reps",
    sets: 3,
    reps: 20,
    perSetSeconds: 0,
    sessionSeconds: 60,
    notes: "Fast knees to chest. Hips stay low and level.",
  },

  // ── CARDIO ────────────────────────────────────────────────
  {
    name: "Jumping Jacks",
    category: "Cardio",
    bodyParts: ["Cardio", "Full Body"],
    exerciseType: "reps",
    sets: 3,
    reps: 30,
    perSetSeconds: 0,
    sessionSeconds: 90,
    notes: "Full range. Steady pace. Land soft.",
  },
  {
    name: "High Knees",
    category: "Cardio",
    bodyParts: ["Cardio", "Legs"],
    exerciseType: "reps",
    sets: 3,
    reps: 30,
    perSetSeconds: 0,
    sessionSeconds: 90,
    notes: "Knees to hip height. Fast. On the balls of your feet.",
  },
  {
    name: "Butt Kicks",
    category: "Cardio",
    bodyParts: ["Cardio", "Legs"],
    exerciseType: "reps",
    sets: 3,
    reps: 30,
    perSetSeconds: 0,
    sessionSeconds: 90,
    notes: "Heels to glutes. Fast. Light on feet.",
  },
  {
    name: "Burpees",
    category: "Cardio",
    bodyParts: ["Full Body", "Cardio"],
    exerciseType: "reps",
    sets: 3,
    reps: 10,
    perSetSeconds: 0,
    sessionSeconds: 120,
    notes: "Squat, plank, push-up, jump. Full commitment on every rep.",
  },
  {
    name: "Jump Rope",
    category: "Cardio",
    bodyParts: ["Cardio"],
    exerciseType: "timer",
    sets: 3,
    reps: 0,
    perSetSeconds: 60,
    sessionSeconds: 180,
    notes: "Light on your feet. Wrists do the work, not the arms.",
  },
  {
    name: "Skater Jumps",
    category: "Cardio",
    bodyParts: ["Cardio", "Legs"],
    exerciseType: "reps",
    sets: 3,
    reps: 20,
    perSetSeconds: 0,
    sessionSeconds: 90,
    notes: "Side to side. Land soft. Swing arms for balance.",
  },
];

export function catalogByCategory(
  category: CatalogCategory,
): CatalogExercise[] {
  return CATALOG.filter((c) => c.category === category);
}
